version: '3.8'

services:
  jenkins-dsl:
    image: tomdesinto/jenkins-dsl-ready
    container_name: jenkins-dsl-container
    ports:
      - "8081:8080"
    volumes:
      - /Users/georgiosgeorgiou/developments/Devops/docker/jenkins:/usr/share/jenkins/ref/jobs/SeedJob/workspace/
    restart: unless-stopped