
services:

  python-integration:
    build: ./integration
    image: python/integration
    container_name: python-integration-container
    ports:
      - "80:8000"
    environment:
      DB_HOST: mysqlRE
      DB_NAME: python # Please change
      DB_USER: root # Please change
      DB_PASSWORD: 123 # Please change
    depends_on:
      mysqlRE:
        condition: service_healthy # Waits for MySQL to be ready
    restart: unless-stopped

  python-uat:
    build: ./python101
    image: python/uat
    container_name: python-uat-container
    ports:
      - "81:8000"
    restart: unless-stopped

  mysqlRE:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123 # Please change
      MYSQL_DATABASE: python # Please change
      MYSQL_USER: pyuser # Please change
      MYSQL_PASSWORD: 123 # Please change
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql/data:/var/lib/mysql